name: Check MkDocs Documentation

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  verify-docs:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗️ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: 🔎 Run MkDocs Build Check
        id: build
        run: |
          echo "🛠️ Checking MkDocs build..."
          mkdocs build > mkdocs_log.txt 2>&1 || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: 📖 Show MkDocs Logs
        run: cat mkdocs_log.txt || true

      - name: ❗ Detect Warnings
        id: warnings
        run: |
          if grep -q "WARNING" mkdocs_log.txt; then
            echo "⚠️ MkDocs built with warnings!"
            echo "HAS_WARNINGS=1" >> $GITHUB_ENV
          fi

      - name: ❌ Fail on Build Error
        if: env.BUILD_FAILED == '1'
        run: |
          echo "❌ MkDocs build failed! Check the logs above."
          exit 1

      - name: ✅ Success Message
        if: env.BUILD_FAILED != '1'
        run: echo "✅ MkDocs build passed!"

      - name: ⚠️ Post Warning if Needed
        if: env.HAS_WARNINGS == '1'
        run: echo "⚠️ MkDocs generated warnings! Check logs."
